### ISSUE TITLE
FlutterNativeTimezonePlugin.kt line 37

### ISSUE THREAD

**Issue by thize** [pinkfish/flutter_native_timezone#28]
FlutterNativeTimezonePlugin.kt line 37
com.whelksoft.flutter_native_timezone.FlutterNativeTimezonePlugin.onMethodCall

Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Ljava/time/ZoneId;

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
       at com.whelksoft.flutter_native_timezone.FlutterNativeTimezonePlugin.onMethodCall(FlutterNativeTimezonePlugin.kt:37)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:6339)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

**Comment by dannyalbuquerque** [comment]
Same problem with sdk < 26

**Comment by pinkfish** [comment]
Ok, submitted the fix that was added and publishing the new package now.  Update to version 2.0.0 and it will have the fixes.

**Comment by otopba** [comment]
Fixed at https://github.com/pinkfish/flutter_native_timezone/issues/25
