### ISSUE TITLE
MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_native_timezone)

### ISSUE THREAD

**Issue by MichaelHipp** [pinkfish/flutter_native_timezone#9]
Using code from the example, I'm getting this exception. Any help?

```
E/flutter ( 3330): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_native_timezone)
E/flutter ( 3330): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 3330): <asynchronous suspension>
E/flutter ( 3330): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 3330): #2      FlutterNativeTimezone.getLocalTimezone (package:flutter_native_timezone/flutter_native_timezone.dart:11:34)
```

**Comment by Tourenathan-G5organisation** [comment]
I'm also getting the same problem on my android device

**Comment by atn832** [comment]
It happened to me too. Running `flutter clean` fixes it.

Someone posted the workaround on a similar issue at https://github.com/flutter/flutter/issues/10912#issuecomment-357932578.

**Comment by simprolog** [comment]
or maybe it's also the R8 build configs:
https://stackoverflow.com/a/66122669/15177345

**Comment by nohli** [comment]
Having this issue on iOS

**Comment by pinkfish** [comment]
I think this is fixed now?
